### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by jvaldezn** [PDFTron/webviewer-annotations-aspnet-sample#1]
Lot of files are mising, nugget only restores references.
![image](https://user-images.githubusercontent.com/25137906/59405016-8a6f9c00-8d6e-11e9-938b-8a1f282ada19.png)

**Comment by mparizeau-pdftron** [comment]
Note that as part of the install instructions you'll need to run `npm install` before opening the sln in Visual Studio. 

I also just pushed a change that removes a couple files that are no longer a part of 5.1 so you can pull, npm install and then try again.
